spring:
  datasource:
    #url: jdbc:h2:file:/data/employee_db
    #username: sa
    #password: password
    #driverClassName: org.h2.Driver
    #MySql
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
    #driverClassName: org.h2.Driver

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
server:
  port : 8081
